### ISSUE TITLE
Add option for mentions in a specific field to references configuration

### ISSUE THREAD

**Issue by keelancook** [kebifurai/TiddlyResearch#17]
It would be great if I had the option in your references configuration tiddler to choose a field other that text for mentions. Configuration would be (1) identify the field and (2) check yes for mentions in that field.

Use Case: I'm using the bibtex plugin to easily import tiddlers for specific book and journal articles that I cite. One of the fields for this is a keywords field. This keywords field has the names of certain "topic tiddlers" that are broad topics for my research. For instance, one of them is "Urban Research". I already have a topic tiddler of that title, and many of my imported references have this as a keyword. If I could chose in your configuration tiddler to have mentions in that field show up, that would populate all of my topic tiddlers with any mentions from bibtex references.

At current, I have to move them into the text field for that to happen.

**Comment by postkevone** [comment]
This sounds like a very specific implementation that doesn't match the way tiddly research was meant to be used. Adding a setting to add a field to the reference plugin would also mean that a user should be able to add more fields, as restricting that setting to only one field doesn't seem like a great approach.
I am sorry but I will not add this feature in the reference plugin because it is very specific, however if you can provide a copy of your wiki I can help you achieve what you need by posting the code you need.

**Comment by keelancook** [comment]
No worries. Seemed like it would give an extra option for connection instead of limiting it.

That said, I've found an elegant enough work around on my part, so I'm good. Thanks for your work on this!
