### ISSUE TITLE
shift-cmd-M Keyboard shortcut does not work as expected

### ISSUE THREAD

**Issue by austinjaney** [kebifurai/TiddlyResearch#3]
shift-cmd-M keyboard shortcut does not work as expected when viewing TiddlyResearch in chrome or TiddlyDesktop and editing a Tiddler.

Expected Behavior: Highlighting marks added
Actual Behavior: opens chrome multiuser switcher

Remapping the keyboard shortcut does not change the behavior but does work correctly in some instances such as adding a Node Note.

**Comment by postkevone** [comment]
I just tried this shortcut and it worked as expected.
I didn't know about the conflict on google chrome, but since you can edit the keyboard shortcut in the control panel, I am not going to change it for the moment.

About the remapping:
Are you on Windows or MacOS?
If you are on windows you will need to change Keyboard shortcuts > highlight > Non-Macintosh platforms only
If you are on mac you will need to change Keyboard shortcuts > highlight > Macintosh platforms only

(I noticed that the popup for the configuration can't be edited when in Krystal view, you can edit it only if you maximize the tiddler or make the tiddler size bigger. I'm going to fix it with the next update.)

**Comment by austinjaney** [comment]
I am on a mac, although I was able to replicate my findings on a pc as well using the ctrl+shift+M key combo on https://kebifurai.github.io/TiddlyResearch/

I can't seem to replicate the same issue in my other TiddlyWiki's. So far, I can rule out the following as a cause since I have them working in another wiki's:
- tiddlyresearch-design: theme tiddlers
- tiddlyresearch-sidebar: sidebar tiddlers
- datepicker: datepicker plugin for tiddlywiki5, based on Pikaday version 1.6.1
- moment: moment.js plugin for TiddlyWiki5
- Project Manager: Simple project managment for Tiddlywiki
- Krystal: (tiddlyresearch's fork) Horizontal Story River
- relink: Relink - flexibility when relinking renamed Tiddlers

I can also say a similar thing happens in Firefox when I remap the key combo , I get a popup that looks like:
![Screen Shot 2020-09-11 at 8 21 09 AM](https://user-images.githubusercontent.com/20212867/92943542-c11be280-f407-11ea-9934-c0a7ff019e26.png)

on the https://kebifurai.github.io/TiddlyResearch/ I get no response at all.

**Comment by postkevone** [comment]
I cannot replicate the issue you are having, are you sure you are using the shortcut when the node editor is opened?

Here's a quick gif that shows that the shortcut is working on https://kebifurai.github.io/TiddlyResearch:

https://i.imgur.com/SpbvJvf.gif

**Comment by professionalPeter** [comment]
I think I figured out the problem here. The mark shortcut doesn't work for me when the Tiddler is open for editing. So I can't use the shortcut in both the regular Tiddler edit area and any node editing areas if the Tiddler is being edited. If I take the Tiddler out of edit mode, then the shortcuts do indeed work when editing nodes.

This problem seems to affect all of the editing keyboard shortcuts (i.e. italics, bold, headings, etc)

BTW, thanks for your work on this. It's already very useful and extremely promising.

**Comment by professionalPeter** [comment]
Interestingly, I can make each shortcut start working when a Tiddler is open for editing by making enabling its editor toolbar button. This doesn't fix all of the editing shortcuts, but only the shortcuts matching the buttons I enabled.

**Comment by postkevone** [comment]
Thanks @professionalPeter for you explanation.
I decided to disable the default editor toolbar buttons by default since tiddly research focuses on single nodes.
Re-activating them also re-enables the shortcuts to work in the default editor.

**Comment by professionalPeter** [comment]
Thanks for your explanation too. Just to be clear, the shortcuts are also disabled in the node editor when the regular Tiddler editor is open. Obviously, I can, and will, close the regular Tiddler editor and happily use the shortcuts in the node editor, but as a newcomer I didn't realize that having that regular editor open was preventing the shortcuts from working. 

Now that I go back and watch the tutorial again I realize that you were always editing nodes with the regular Tiddler editor closed, but as someone new to this I didn't immediately notice that. So my workflow was something like:
1. Create new tiddler
1. Create a new node
1. Start editing the node (while wondering why shortcuts aren't working)

where it needs to be:

1. Create new tiddler
1. Save Tiddler (thus closing the Tiddler editor)
1. Create a new node
1. Start editing the node (enjoy the happiness and joy of the shortcuts)

Anyway, everything is working now for me, so thanks. I'm just passing this along in case it's helpful to you.

**Comment by postkevone** [comment]
I only tested the shortcuts in the streams editor without realizing that they were not available in the default one.
In the next update I'm going to restore the editor toolbars that have custom shortcuts so that you can use them everywhere.
Thanks for the feedback!

**Comment by postkevone** [comment]
> I only tested the shortcuts in the streams editor without realizing that they were not available in the default one.
> In the next update I'm going to restore the editor toolbars that have custom shortcuts so that you can use them everywhere.
> Thanks for the feedback!

Fixed with v1.3
